name: Build and test

on: [push]

jobs:
 build:
   runs-on: ubuntu-latest

   steps:
   - name: git repository
     uses: actions/checkout@v3

   - name: setup nodejs
     uses: actions/setup-nodejs@v3
     with:
       node-version: '14'

   - name: install dependencies
     run: npm install

   - name: build code
     run: npm run build

   - name: test code
     run: npm run test

    
   
